### ISSUE TITLE
Deprecated feature in jQuery update

### ISSUE THREAD

**Issue by kp52** [michael-big/AvenirCMS#1]
Glad to see someone interested in continuing with Clipper! Freut mich, dass jemand sich noch fuer Clipper interessiert!

I have been using jQuery 1.12.4 in my own version based on Clipper 1.3.3. Two uses of the deprecated ".live" method need to be replaced:

manager/frames/tree.php l.44:
change `jQuery('#Button10.treeButton').live('click', function()`
to `jQuery('body').on('click', '#Button10.treeButton', function()`

assets/modules/resmanager/templates/main.tpl l.27:
change `$('input[id^=tv].DatePicker').live('focus', function()`
to `$('body').on('focus', 'input[id^=tv].DatePicker', function()`

**Comment by michael-big** [comment]
I have already replaced deprecated .live method in both files.
