### ISSUE TITLE
References to non-existent field

### ISSUE THREAD

**Issue by kp52** [michael-big/AvenirCMS#11]
Current Develop branch (v1.4) contains references to an "alias_visible" field in the site_content table. Installing a new site is not affected, but trying to import an existing Clipper 1.3.3 site using advanced upgrade failed with an error referring to "unknown column 'alias_visible' in 'field list'"

./assets/snippets/breadcrumbs/snippet.breadcrumbs.php:145:	 $tempCrumb = 
$modx->getPageInfo($parent,0,"id,parent,pagetitle,longtitle,menutitle,description,published,hidemenu,template,alias_visible");

./manager/includes/document.parser.class.inc.php:4000:            WHERE sc.parent = {$parentid} AND sc.alias_visible = '0' GROUP BY children.id;"

./manager/processors/cache_sync.class.processor.php:34:			$qh = $modx->db->select('id, IF(alias=\'\', id, alias) AS alias, parent, alias_visible', $modx->getFullTableName('site_content'));

./manager/processors/save_tmplvars.processor.php:113:		if(in_array($name, array('id', 'type', 'contentType', 'pagetitle', 'longtitle', 'description', 'alias', 'link_attributes', 'published', 'pub_date', 'unpub_date', 'parent', 'isfolder', 'introtext', 'content', 'richtext', 'template', 'menuindex', 'searchable', 'cacheable', 'createdby', 'createdon', 'editedby', 'editedon', 'deleted', 'deletedon', 'deletedby', 'publishedon', 'publishedby', 'menutitle', 'donthit', 'haskeywords', 'hasmetatags', 'privateweb', 'privatemgr', 'content_dispo', 'hidemenu','alias_visible'))) {

**Comment by michael-big** [comment]
Removed.
