### ISSUE TITLE
elFinder directory name

### ISSUE THREAD

**Issue by kp52** [michael-big/AvenirCMS#6]
Avenir 1.3.5 demo site (Xubuntu 16.04/Apache 2.4/PHP 7.1):

Error **URL /manager/media/browser/elFinder/browse.php was not found on this server** when you click on `Insert` in an image TV (e.g. recipe images)

Works when directory is renamed from **manager/media/browser/elfinder** to **manager/media/browser/elFinder**

**Comment by michael-big** [comment]
Fixed
